from snmpv3 import SNMPV3_SECURITYNAME, SNMPV3_SECURITYLEVEL,SNMPV3_AUTHPROTOCOL, SNMPV3_PRIVPROTOCOL, SNMPV3_AUTHPASSPHRASE, SNMPV3_PRIVPASSPHRASE, SNMPV3_CONTEXTNAME

# SNMP import
SNMPV3_SECURITYNAME
SNMPV3_SECURITYLEVEL
SNMPV3_AUTHPROTOCOL
SNMPV3_PRIVPROTOCOL
SNMPV3_AUTHPASSPHRASE 
SNMPV3_PRIVPASSPHRASE
SNMPV3_CONTEXTNAME
# GroupID and TemplateID
GROUPID1 = "1" # Device GroupID
# GROUPID2 = "2" # You can do multiple groupids
TEMPLATEID1 = "1" # Device SNMP Template
# TEMPLATEID2 = "2" # You can do multiple templateids if they don't overlap